# Generated by Django 5.0.4 on 2024-04-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filmes',
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
